version: '3.7'

services:
  server:
    image: jetbrains/teamcity-server
    volumes:
      - ./logs:/opt/teamcity/logs
      - ./data:/data/teamcity_server/datadir
    ports:
      - 8111:8111

  agent_1:
    image: jetbrains/teamcity-agent
    environment:
      SERVER_URL: http://server:8111
      AGENT_NAME: agent_first
    volumes:
      - ./agent/conf:/data/teamcity_agent/conf
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - server
    depends_on:
      - server
